# **Import library tensorflow**

In [48]:
import tensorflow as tf

# **Membuat tensor random dengan dimensi (5, 5)**

In [49]:
random_tensor = tf.random.normal([5, 5], dtype=float, stddev = 1, mean=0.5, seed=5)
random_tensor.numpy()

array([[ 0.53974456,  1.0504236 ,  1.5510736 , -0.82870233,  1.1358536 ],
       [ 1.0551676 ,  1.1375024 ,  0.3888693 , -0.16569763, -0.13128918],
       [ 1.608872  ,  0.44706893, -0.44347942,  2.0170941 ,  0.7321839 ],
       [-2.4313595 , -0.26565975,  1.530392  ,  1.8295895 ,  0.46149746],
       [ 0.9867941 ,  0.22037265, -1.0986222 ,  1.3417094 ,  2.667009  ]],
      dtype=float32)

# **Membuat tensor berisi bilangan prima dengan dimensi (5, 5)**

### Membuat list berisi bilangan prima kemudian mengubahnya ke tensor berdimensi (5, 5)

In [50]:
prima = []
a = 2;
i = 0
while i < 25:
  prime = True
  j = 2
  while j*j <= a:
    if(a%j==0):
      prime = False
      break
    j+=1
  if(prime):
    prima.append(a)
    i+=1
  a+=1

prime_tensor = tf.convert_to_tensor(prima, dtype=float)
prime_tensor = tf.reshape(prime_tensor, [5, 5])
prime_tensor.numpy()

array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)

# **Menampilkan dimensi dari random_tensor dan prime_tensor**

In [51]:
print("Dimesi random_tensor: ", random_tensor.shape)
print("Dimesi prime_tensor: ", prime_tensor.shape)

Dimesi random_tensor:  (5, 5)
Dimesi prime_tensor:  (5, 5)


# **Menampilkan minimal 5 perhitungan aritmatika dari random_tensor dan prime_tensor**

In [52]:
print("Penjumlahan: \n", tf.add(random_tensor, prime_tensor).numpy())
print('')
print("Pengurangan: \n", tf.subtract(random_tensor, prime_tensor).numpy())
print('')
print("Perkalian: \n", tf.multiply(random_tensor, prime_tensor).numpy())
print('')
print("Pembagian: \n", tf.divide(random_tensor, prime_tensor).numpy())
print('')
print("Pemangkatan: \n", tf.pow(random_tensor, prime_tensor).numpy())
print('')
print("Akar random_tensor: \n", tf.math.sqrt(random_tensor).numpy())
print('')
print("Akar prime_tensor: \n", tf.math.sqrt(prime_tensor).numpy())
print('')
print("Logaritma random_tensor: \n", tf.math.log(random_tensor).numpy())
print('')
print("Logaritma prime_tensor: \n", tf.math.log(prime_tensor).numpy())

Penjumlahan: 
 [[ 2.5397446  4.0504236  6.5510736  6.1712976 12.135854 ]
 [14.055167  18.137503  19.38887   22.834303  28.868711 ]
 [32.60887   37.447067  40.556522  45.017094  47.732185 ]
 [50.56864   58.73434   62.53039   68.82959   71.461494 ]
 [73.98679   79.220375  81.901375  90.34171   99.66701  ]]

Pengurangan: 
 [[ -1.4602554  -1.9495764  -3.4489264  -7.8287024  -9.864146 ]
 [-11.944833  -15.862497  -18.61113   -23.165697  -29.131289 ]
 [-29.391129  -36.552933  -41.443478  -40.982906  -46.267815 ]
 [-55.43136   -59.26566   -59.46961   -65.17041   -70.538506 ]
 [-72.01321   -78.779625  -84.098625  -87.65829   -94.33299  ]]

Perkalian: 
 [[   1.0794891    3.1512709    7.7553678   -5.800916    12.4943905]
 [  13.717178    19.337542     7.3885164   -3.8110456   -3.8073864]
 [  49.875034    16.54155    -18.182655    86.73505     34.412643 ]
 [-128.86206    -15.673925    93.35391    122.5825      32.76632  ]
 [  72.03597     17.40944    -91.185646   119.41213    258.6999   ]]

Pembag

# **Menampilkan nilai minimum dan maksimum dari random_tensor**

### Baris dan kolom maksimum

In [53]:
print("Baris maksimum ", tf.argmax(random_tensor, axis=0).numpy())
print("Kolom maksimum ", tf.argmax(random_tensor, axis=1).numpy())

Baris maksimum  [2 1 0 2 4]
Kolom maksimum  [2 1 3 3 4]


### Baris dan Kolom minimum

In [54]:
print("Baris minimum ", tf.argmin(random_tensor, axis=0).numpy())
print("Kolom miniimum ", tf.argmin(random_tensor, axis=1).numpy())

Baris minimum  [3 3 4 0 1]
Kolom miniimum  [3 3 2 0 2]


# **Menampilkan hasil penggabungan varaiabel random_tensor dan prime_tensor**

## Menggabungkan berdasarkan baris

In [55]:
tf.concat([random_tensor,prime_tensor], axis=0).numpy()

array([[ 0.53974456,  1.0504236 ,  1.5510736 , -0.82870233,  1.1358536 ],
       [ 1.0551676 ,  1.1375024 ,  0.3888693 , -0.16569763, -0.13128918],
       [ 1.608872  ,  0.44706893, -0.44347942,  2.0170941 ,  0.7321839 ],
       [-2.4313595 , -0.26565975,  1.530392  ,  1.8295895 ,  0.46149746],
       [ 0.9867941 ,  0.22037265, -1.0986222 ,  1.3417094 ,  2.667009  ],
       [ 2.        ,  3.        ,  5.        ,  7.        , 11.        ],
       [13.        , 17.        , 19.        , 23.        , 29.        ],
       [31.        , 37.        , 41.        , 43.        , 47.        ],
       [53.        , 59.        , 61.        , 67.        , 71.        ],
       [73.        , 79.        , 83.        , 89.        , 97.        ]],
      dtype=float32)

## Menggabungkan berdasarkan kolom

In [56]:
tf.concat([random_tensor,prime_tensor], axis=1).numpy()

array([[ 0.53974456,  1.0504236 ,  1.5510736 , -0.82870233,  1.1358536 ,
         2.        ,  3.        ,  5.        ,  7.        , 11.        ],
       [ 1.0551676 ,  1.1375024 ,  0.3888693 , -0.16569763, -0.13128918,
        13.        , 17.        , 19.        , 23.        , 29.        ],
       [ 1.608872  ,  0.44706893, -0.44347942,  2.0170941 ,  0.7321839 ,
        31.        , 37.        , 41.        , 43.        , 47.        ],
       [-2.4313595 , -0.26565975,  1.530392  ,  1.8295895 ,  0.46149746,
        53.        , 59.        , 61.        , 67.        , 71.        ],
       [ 0.9867941 ,  0.22037265, -1.0986222 ,  1.3417094 ,  2.667009  ,
        73.        , 79.        , 83.        , 89.        , 97.        ]],
      dtype=float32)

# **Menampilkan hasil sorting secara descending dari random_tensor dan prime_tensor**

In [57]:
print("Sort random_tensor secara descending:\n", tf.sort(random_tensor, direction="DESCENDING").numpy())
print('')
print("Sort prime_tensor secara descending:\n", tf.sort(prime_tensor, direction="DESCENDING").numpy())

Sort random_tensor secara descending:
 [[ 1.5510736   1.1358536   1.0504236   0.53974456 -0.82870233]
 [ 1.1375024   1.0551676   0.3888693  -0.13128918 -0.16569763]
 [ 2.0170941   1.608872    0.7321839   0.44706893 -0.44347942]
 [ 1.8295895   1.530392    0.46149746 -0.26565975 -2.4313595 ]
 [ 2.667009    1.3417094   0.9867941   0.22037265 -1.0986222 ]]

Sort prime_tensor secara descending:
 [[11.  7.  5.  3.  2.]
 [29. 23. 19. 17. 13.]
 [47. 43. 41. 37. 31.]
 [71. 67. 61. 59. 53.]
 [97. 89. 83. 79. 73.]]
